#!/bin/bash 

# Case Statement Demo 

echo "Please choose one of the option from below: "
echo 
echo "a  --> Display Date and Time" 
echo "b  --> List of all directories"
echo "c  --> List of all user logged in" 
echo "d  --> List the sytem uptime" 
echo 
      read choice 
      case $choice in 
    a) date;;
    b) ls -ltr ;;
    c) who;;
    d) uptime;;
    *) echo Inavlid choice --Bye!
esac
