#!/bin/bash 

#Author: nitesh Kumar
#Date :  10/08/2020
#Description : ping   ip address  in files to find wich is reachable  or not
#Modified : 10/08/2020
#Date_formate -- MM/DD/YYYY


#************************************************Program details descritption********************************************
# Command -- Ping is comamnd to ping ip 
# -c<number> number of times want to ping 
# $? will  return  the output of abpve command in our case ping -c5 192.168.0.1  ..if will zero when it able to ping 
# &> /dev/null --> to rediect the ouput to null file 
#************************************************************************************************************************


hostname=/home/centos/myscripts/myhosts

for ip in $(cat $hostname) 
  	do 
  	 ping -c1 $ip &> /dev/null
          if [ $? -eq 0 ] 
          then 
	      echo  $ip is ok 
          else 
	      echo $ip is NOT OK 
  	fi
	done       
